package com.example.krustykrab.model.MenuModel;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@ToString
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "kurst-krab")
public class Menu {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String imgUrl;

    @DynamoDBAttribute
    private Double price;

    @DynamoDBAttribute
    private Long availableQty;

}
