package com.example.krustykrab.model.order;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.krustykrab.model.MenuModel.Menu;
import com.example.krustykrab.model.customer.Customer;
import com.example.krustykrab.translators.CustomerTranslator;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;
@ToString
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Orders")
public class Order {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String customerId;
    @DynamoDBAttribute
    private String date;
    @DynamoDBAttribute
    private List<Menu> ordered;
}
